### ISSUE TITLE
Humanize file sizes

### ISSUE THREAD

**Issue by rominf** [de-odex/suru#2]
First of all, thanks for your library!

I use it to show the progress of downloading some big files (see https://github.com/rominf/nim-downloader). Currently, the progress bar looks like this:
![image](https://user-images.githubusercontent.com/3449635/105608231-70e86000-5dab-11eb-80fd-d043ec842f99.png)

It would be great to be able to make sizes human-readable like:
26.2 MiB/76.0 MiB

**Comment by disruptek** [comment]
See the bytes2human module or my grok module (grok/kute).

**Comment by rominf** [comment]
OK, I found that there is a function in the standard library: https://nim-lang.org/docs/strutils.html#formatSize%2Cint64%2Cchar. I applied this function and got the result that I wanted.
