### ISSUE TITLE
Suru does not compile on nim 2.0

### ISSUE THREAD

**Issue by YamatoSecurity** [de-odex/suru#8]
When trying to compile with nim 2.0 I get this error:
```
suru.nim(241, 14) Error: type mismatch
Expression: setup(sbc[].bar, iterableLengths)
  [1] sbc[].bar: SuruBar
  [2] iterableLengths: varargs[int]

Expected one of (first mismatch at [position]):
[1] proc setup(sbc: ptr SuruBarController; iterableLengths: varargs[int])
[2] proc setup(sb: var SuruBar)
```

**Comment by fukusuket** [comment]
This issue seems to be fixed in [this pull request](https://github.com/de-odex/suru/pull/4) and I have confirmed that it does not occur in the main branch latest commit f6f1e607c585b2bc2f71309996643f0555ff6349.

**Comment by sgmoore** [comment]
This fix doesn't seem to be included when you install suru using nimble (with is getting tagged version: v0.3.1from 2021).

It is possible to fix that?
